connector.name=iceberg

# Iceberg REST catalog
iceberg.catalog.type=rest
iceberg.rest-catalog.uri=http://seaweedfs:8181
iceberg.rest-catalog.warehouse=s3://f1-iceberg

# SeaweedFS Iceberg REST authentication
iceberg.rest-catalog.security=OAUTH2
iceberg.rest-catalog.oauth2.credential=${ENV:AWS_ACCESS_KEY_ID}:${ENV:AWS_SECRET_ACCESS_KEY}
iceberg.rest-catalog.oauth2.server-uri=http://seaweedfs:8181/v1/oauth/tokens
iceberg.rest-catalog.vended-credentials-enabled=false

# S3-compatible object storage
fs.s3.enabled=true

s3.endpoint=http://seaweedfs:8333
s3.region=us-east-1
s3.path-style-access=true

s3.aws-access-key=${ENV:AWS_ACCESS_KEY_ID}
s3.aws-secret-key=${ENV:AWS_SECRET_ACCESS_KEY}

# Iceberg defaults
iceberg.file-format=PARQUET
iceberg.compression-codec=ZSTD
