from __future__ import annotations

import pytest

from src.common import find_missing_races


# ============================================================
# TEST DOUBLES
# ============================================================


class FakeTrinoUserError(Exception):
    """
    Minimal stand-in for trino.exceptions.TrinoUserError.

    The production code checks the exception's error_name
    attribute to distinguish expected cold-start conditions
    such as TABLE_NOT_FOUND and SCHEMA_NOT_FOUND from genuine
    Trino failures.
    """

    def __init__(
        self,
        error_name: str,
    ) -> None:

        super().__init__(
            error_name
        )

        self.error_name = (
            error_name
        )


class FakeCursor:
    """
    Small fake Trino cursor used by the unit tests.
    """

    def __init__(
        self,
        rows=None,
        exception=None,
    ) -> None:

        self.rows = (
            rows
            if rows is not None
            else []
        )

        self.exception = (
            exception
        )

        self.query = None

    def execute(
        self,
        query,
    ) -> None:

        self.query = (
            query
        )

        if self.exception:

            raise self.exception

    def fetchall(
        self,
    ):

        return self.rows

    def close(
        self,
    ) -> None:

        pass


class FakeConnection:
    """
    Small fake Trino connection used by the unit tests.
    """

    def __init__(
        self,
        cursor,
    ) -> None:

        self.fake_cursor = (
            cursor
        )

    def cursor(
        self,
    ):

        return self.fake_cursor

    def close(
        self,
    ) -> None:

        pass


def install_fake_connection(
    monkeypatch,
    rows=None,
    exception=None,
):
    """
    Replace the real Trino connection with a fake connection.

    Returns the fake cursor so individual tests may inspect
    the SQL generated by the production code if required.
    """

    cursor = FakeCursor(
        rows=rows,
        exception=exception,
    )

    connection = FakeConnection(
        cursor
    )

    monkeypatch.setattr(
        find_missing_races,
        "connect",
        lambda **kwargs: connection,
    )

    return cursor


# ============================================================
# get_event_slugs
# ============================================================


def test_get_event_slugs_returns_unique_events(
    monkeypatch,
):
    """
    Event slugs returned by Trino should be converted into
    a unique Python set.

    NULL values should be ignored.
    """

    install_fake_connection(
        monkeypatch,
        rows=[
            (
                "australian-grand-prix",
            ),
            (
                "canadian-grand-prix",
            ),
            (
                "canadian-grand-prix",
            ),
            (
                None,
            ),
        ],
    )

    result = (
        find_missing_races.get_event_slugs(
            "iceberg.bronze.laps",
            2026,
            "R",
        )
    )

    assert result == {
        "australian-grand-prix",
        "canadian-grand-prix",
    }


def test_get_event_slugs_generates_expected_query(
    monkeypatch,
):
    """
    Verify that the query contains the requested table,
    season, and session.
    """

    cursor = (
        install_fake_connection(
            monkeypatch,
            rows=[],
        )
    )

    find_missing_races.get_event_slugs(
        "iceberg.bronze.results",
        2026,
        "R",
    )

    assert (
        "iceberg.bronze.results"
        in cursor.query
    )

    assert (
        "season = 2026"
        in cursor.query
    )

    assert (
        "session_type = 'R'"
        in cursor.query
    )


# ============================================================
# get_event_drivers
# ============================================================


def test_get_event_drivers_groups_by_event(
    monkeypatch,
):
    """
    Driver rows should be grouped into one set per race.
    Duplicate drivers must collapse automatically.
    """

    install_fake_connection(
        monkeypatch,
        rows=[
            (
                "canadian-grand-prix",
                "HAM",
            ),
            (
                "canadian-grand-prix",
                "VER",
            ),
            (
                "canadian-grand-prix",
                "HAM",
            ),
            (
                "monaco-grand-prix",
                "LEC",
            ),
        ],
    )

    result = (
        find_missing_races.get_event_drivers(
            "iceberg.bronze.telemetry",
            2026,
            "R",
        )
    )

    assert result == {
        "canadian-grand-prix": {
            "HAM",
            "VER",
        },
        "monaco-grand-prix": {
            "LEC",
        },
    }


def test_get_event_drivers_ignores_null_values(
    monkeypatch,
):
    """
    Invalid rows containing NULL event or driver values
    should not become expected telemetry drivers.
    """

    install_fake_connection(
        monkeypatch,
        rows=[
            (
                "canadian-grand-prix",
                "HAM",
            ),
            (
                "canadian-grand-prix",
                None,
            ),
            (
                None,
                "VER",
            ),
            (
                None,
                None,
            ),
        ],
    )

    result = (
        find_missing_races.get_event_drivers(
            "iceberg.bronze.telemetry",
            2026,
            "R",
        )
    )

    assert result == {
        "canadian-grand-prix": {
            "HAM",
        },
    }


# ============================================================
# COLD-START BEHAVIOR
# ============================================================


def test_get_event_slugs_cold_start_table_not_found(
    monkeypatch,
):
    """
    A missing Iceberg table is a valid cold-start state.

    Discovery should interpret TABLE_NOT_FOUND as an empty
    dataset rather than crashing the DAG.
    """

    monkeypatch.setattr(
        find_missing_races,
        "TrinoUserError",
        FakeTrinoUserError,
    )

    install_fake_connection(
        monkeypatch,
        exception=FakeTrinoUserError(
            "TABLE_NOT_FOUND"
        ),
    )

    result = (
        find_missing_races.get_event_slugs(
            "iceberg.bronze.laps",
            2026,
            "R",
        )
    )

    assert result == set()


def test_get_event_slugs_cold_start_schema_not_found(
    monkeypatch,
):
    """
    A missing Iceberg schema is also a valid cold-start state.
    """

    monkeypatch.setattr(
        find_missing_races,
        "TrinoUserError",
        FakeTrinoUserError,
    )

    install_fake_connection(
        monkeypatch,
        exception=FakeTrinoUserError(
            "SCHEMA_NOT_FOUND"
        ),
    )

    result = (
        find_missing_races.get_event_slugs(
            "iceberg.silver.silver_telemetry",
            2026,
            "R",
        )
    )

    assert result == set()


def test_get_event_drivers_cold_start_table_not_found(
    monkeypatch,
):
    """
    Driver discovery must also survive a missing table during
    a full cold rebuild.
    """

    monkeypatch.setattr(
        find_missing_races,
        "TrinoUserError",
        FakeTrinoUserError,
    )

    install_fake_connection(
        monkeypatch,
        exception=FakeTrinoUserError(
            "TABLE_NOT_FOUND"
        ),
    )

    result = (
        find_missing_races.get_event_drivers(
            "iceberg.bronze.telemetry",
            2026,
            "R",
        )
    )

    assert result == {}


# ============================================================
# REAL FAILURE BEHAVIOR
# ============================================================


def test_get_event_slugs_does_not_hide_unexpected_errors(
    monkeypatch,
):
    """
    Only known cold-start errors should be suppressed.

    Permission failures and other unexpected Trino errors
    must still fail loudly.
    """

    monkeypatch.setattr(
        find_missing_races,
        "TrinoUserError",
        FakeTrinoUserError,
    )

    install_fake_connection(
        monkeypatch,
        exception=FakeTrinoUserError(
            "PERMISSION_DENIED"
        ),
    )

    with pytest.raises(
        FakeTrinoUserError
    ):

        find_missing_races.get_event_slugs(
            "iceberg.bronze.laps",
            2026,
            "R",
        )
