coordinator=true
node-scheduler.include-coordinator=true
discovery.uri=http://localhost:8080
catalog.management=${ENV:CATALOG_MANAGEMENT}

query.max-memory-per-node=1500MB
query.max-memory=1500MB
query.max-total-memory=2GB
memory.heap-headroom-per-node=1GB
